trigger: none

pr:
  branches:
    include:
      - main

parameters:
- name: agentPool
  displayName: Build agent pool
  type: string
  default: microsoft-hosted
  values:
  - microsoft-hosted
  - self-hosted

stages:
- stage: Build
  displayName: Build solution
  jobs:
  - ${{ if eq(parameters.agentPool, 'self-hosted') }}:
    - template: templates/dotnet-build-job.yml
      parameters:
        pool:
          name: Default
  - ${{ else }}:
    - template: templates/dotnet-build-job.yml
      parameters:
        pool:
          vmImage: ubuntu-latest